### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by somebody1234**

### CODE REVIEW

**Comment by Ahsome** [comment]
@somebody1234, why the closure?

**Comment by somebody1234** [comment]
@Ahsome because I've decided to work on it in my fork instead - doesn't seem very likely that @Lewenski is very active right now.

**Comment by Ahsome** [comment]
@somebody1234, ahh, that makes sense. I'll tell Lewen to see his GitHub page tomorrow

**Comment by somebody1234** [comment]
@Ahsome I can tell him, but there's no point if he doesn't want to code any more (for now, at least).

**Comment by Ahsome** [comment]
He does, @somebody1234. It just that he's been busy with studies

**Comment by somebody1234** [comment]
@Ahsome Oh, okay

**Pull request closed without merging**
